/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TextVariant } from "./components/k-text/k-text";
export { TextVariant } from "./components/k-text/k-text";
export namespace Components {
    /**
     * Header component mirroring a real design-system header:
     * shadow: true, named slots (start / end), an inner logo with inline SVG.
     */
    interface KHeader {
        /**
          * @default 'Home'
         */
        "logoAriaLabel": string;
    }
    /**
     * Minimal text component mirroring a real Stencil design-system primitive:
     * shadow: true, a styled <p>, and a default <slot>.
     */
    interface KText {
        /**
          * @default 'body'
         */
        "variant": TextVariant;
    }
}
declare global {
    /**
     * Header component mirroring a real design-system header:
     * shadow: true, named slots (start / end), an inner logo with inline SVG.
     */
    interface HTMLKHeaderElement extends Components.KHeader, HTMLStencilElement {
    }
    var HTMLKHeaderElement: {
        prototype: HTMLKHeaderElement;
        new (): HTMLKHeaderElement;
    };
    /**
     * Minimal text component mirroring a real Stencil design-system primitive:
     * shadow: true, a styled <p>, and a default <slot>.
     */
    interface HTMLKTextElement extends Components.KText, HTMLStencilElement {
    }
    var HTMLKTextElement: {
        prototype: HTMLKTextElement;
        new (): HTMLKTextElement;
    };
    interface HTMLElementTagNameMap {
        "k-header": HTMLKHeaderElement;
        "k-text": HTMLKTextElement;
    }
}
declare namespace LocalJSX {
    /**
     * Header component mirroring a real design-system header:
     * shadow: true, named slots (start / end), an inner logo with inline SVG.
     */
    interface KHeader {
        /**
          * @default 'Home'
         */
        "logoAriaLabel"?: string;
    }
    /**
     * Minimal text component mirroring a real Stencil design-system primitive:
     * shadow: true, a styled <p>, and a default <slot>.
     */
    interface KText {
        /**
          * @default 'body'
         */
        "variant"?: TextVariant;
    }

    interface KHeaderAttributes {
        "logoAriaLabel": string;
    }
    interface KTextAttributes {
        "variant": TextVariant;
    }

    interface IntrinsicElements {
        "k-header": Omit<KHeader, keyof KHeaderAttributes> & { [K in keyof KHeader & keyof KHeaderAttributes]?: KHeader[K] } & { [K in keyof KHeader & keyof KHeaderAttributes as `attr:${K}`]?: KHeaderAttributes[K] } & { [K in keyof KHeader & keyof KHeaderAttributes as `prop:${K}`]?: KHeader[K] };
        "k-text": Omit<KText, keyof KTextAttributes> & { [K in keyof KText & keyof KTextAttributes]?: KText[K] } & { [K in keyof KText & keyof KTextAttributes as `attr:${K}`]?: KTextAttributes[K] } & { [K in keyof KText & keyof KTextAttributes as `prop:${K}`]?: KText[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Header component mirroring a real design-system header:
             * shadow: true, named slots (start / end), an inner logo with inline SVG.
             */
            "k-header": LocalJSX.IntrinsicElements["k-header"] & JSXBase.HTMLAttributes<HTMLKHeaderElement>;
            /**
             * Minimal text component mirroring a real Stencil design-system primitive:
             * shadow: true, a styled <p>, and a default <slot>.
             */
            "k-text": LocalJSX.IntrinsicElements["k-text"] & JSXBase.HTMLAttributes<HTMLKTextElement>;
        }
    }
}
